In [1]:
! pip install folium

Collecting folium
  Downloading folium-0.12.1-py2.py3-none-any.whl (94 kB)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from folium) (2.25.1)
Collecting branca>=0.3.0
  Downloading branca-0.4.2-py3-none-any.whl (24 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from folium) (1.20.1)
Requirement already satisfied: jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from folium) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2.10)
Installing collected packages: branca, folium
Successfully installed branca-0.4.2 folium-0.12.1

In [8]:
import pandas as pd
df = pd.read_csv('csv/경상남도_양산시_도시공원정보_20210521_1621587827428_21597.csv', 'r', encoding = "euc-kr")
df

    관리번호,공원명,공원구분,소재지도로명주소,소재지지번주소,위도,경도,공원면적,공원보유시설(운동시설),공원보유시설(유희시설),공원보유시설(편익시설),공원보유시설(교양시설),공원보유시설(기타시설),지정고시일,관리기관명,전화번호,데이터기준일자
0    48330-00001,춘추근린공원,근린공원,,경상남도 양산시 교동 산55-1,35....
1    48330-00002,신북안 어린이공원,어린이공원,,경상남도 양산시 북부동 486-...
2    48330-00003,산막 어린이공원,어린이공원,,경상남도 양산시 산막동 309-1...
3    48330-00004,유산근린공원,근린공원,,경상남도 양산시 유산동 산50-1,35...
4    48330-00005,가촌신기 어린이공원,어린이공원,,경상남도 양산시 물금읍 가촌리...
..                                                 ...
96   48330-00097,10호 근린공원(10-C),근린공원,,경상남도 양산시 물금읍 ...
97   48330-00098,초산어린이공원,어린이공원,,경상남도 양산시 하북면 초산리 31...
98   48330-00099,대바웃골,소공원,,경상남도 양산시 상북면 석계리 산7,35.4...
99   48330-00100,팥밭골,소공원,,경상남도 양산시 상북면 석계리 산7-1,35....
100  48330-00101,봉수대근린공원,근린공원,,경상남도 양산시 상북면 석계리 337...

[101 rows x 1 columns]

In [25]:
import csv
import folium

# 파일 읽기
file = open('csv/경상남도_양산시_도시공원정보_20210521_1621587827428_21597.csv', 'r', encoding = "euc-kr")
rdr = csv.reader(file)

next(rdr, None) #컬럼명 skip

# 읽은 파일 내용보기(공원명[1], 위도[5], 경도[6])
for idx, tmp in enumerate(rdr):
    if idx == 0: # 최초 1번 객체 만들기 시작 주소의 중심이 location에 정의된 곳
        map_data = folium.Map(location=[ float(tmp[5]), float(tmp[6]) ], zoom_size=12, zoom_start=13 )
    #71개
    folium.Marker([ float(tmp[5]), float(tmp[6]) ], popup = tmp[1] ).add_to(map_data).add_to(map_data)
        
map_data.save('map/ex01.html') # 지도를 html 저장

In [29]:
import csv
import requests
import pandas as pd

# 데이터 1000개 => 800개 훈련, 200개 테스트 데이터
csv_url = "http://ihongss.com/resources/train.csv" # 타이타닉 훈련 데이터

with requests.Session() as s:
    download = s.get(csv_url)
    decode_content = download.content.decode('utf-8')
    
    file = csv.reader(decode_content.splitlines(), delimiter=",")
    
    data = list(file) #[ [컬럼명], [실제데이터], [실제데이터],.......[실제데이터]]
#     for tmp in data:
#         print(tmp)
    df = pd.DataFrame(data[1:], columns = data[0])
df

df.describe()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
count,891,891,891,891,891,891,891,891,891,891,891
unique,2,3,891,2,89,7,7,681,248,148,4
top,0,3,"Webber, Mr. James",male,,0,0,347082,8.05,,S
freq,549,491,1,577,177,608,678,7,43,687,644